"""
Tests that mart_pitstop_features has no nulls in the columns used by the ML model.
Since this table is generated by a dbt model, these tests run against a mock
DataFrame that simulates what the Gold table should look like.
"""

import pandas as pd
import numpy as np
import pytest

FEATURE_COLS = [
    "compound_encoded",
    "tyre_age_at_pit",
    "lap_time_degradation_slope",
    "race_progress_at_pit",
    "qualifying_position",
    "n_stops_so_far",
    "circuit_avg_pit_time_loss",
    "weather_is_dry",
    "constructor_avg_pitstop_duration",
]


def make_valid_features(n=10) -> pd.DataFrame:
    return pd.DataFrame({
        "year":                           [2023] * n,
        "round":                          list(range(1, n + 1)),
        "driver_id":                      ["hamilton"] * n,
        "compound_encoded":               [1] * n,
        "tyre_age_at_pit":                [15] * n,
        "lap_time_degradation_slope":     [0.05] * n,
        "race_progress_at_pit":           [0.4] * n,
        "qualifying_position":            [3] * n,
        "n_stops_so_far":                 [1] * n,
        "circuit_avg_pit_time_loss":      [22.5] * n,
        "weather_is_dry":                 [1] * n,
        "constructor_avg_pitstop_duration": [22.1] * n,
        "pit_window_class":               ["MID"] * n,
    })


def validate_no_nulls(df: pd.DataFrame, cols: list) -> list:
    """Returns list of columns that have nulls."""
    return [c for c in cols if df[c].isna().any()]


def test_valid_features_have_no_nulls():
    df = make_valid_features()
    bad_cols = validate_no_nulls(df, FEATURE_COLS)
    assert bad_cols == [], f"Null values found in: {bad_cols}"


def test_detects_null_tyre_age():
    df = make_valid_features()
    df.loc[0, "tyre_age_at_pit"] = np.nan
    bad_cols = validate_no_nulls(df, FEATURE_COLS)
    assert "tyre_age_at_pit" in bad_cols


def test_all_feature_cols_present():
    df = make_valid_features()
    for col in FEATURE_COLS:
        assert col in df.columns, f"Missing feature column: {col}"


def test_compound_encoded_valid_range():
    df = make_valid_features()
    assert df["compound_encoded"].isin([0, 1, 2, 3]).all()


def test_race_progress_between_0_and_1():
    df = make_valid_features()
    assert (df["race_progress_at_pit"] >= 0).all()
    assert (df["race_progress_at_pit"] <= 1).all()
